sudo: required

language: generic

services:
 - docker

before_install:
 - echo " start creating an image with dockerfile"
 - docker build -t hyeunlee/docker-react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true  hyeunlee/docker-react-app npm run test -- --coverage

after_success:
 - echo " Test 1'st Success"
